hl.foreground("Boolean", col.bright_magenta)
hl.foreground("Character", col.green:lighten(5))
hl.foreground("Comment", col.bright_black:brighten(5):lighten(20))
hl.foreground("SpecialComment", col.yellow:increase_red(3):darken(3))
hl.foreground("Conceal", col.bright_black:lighten(2))
hl.foreground("Conditional", col.red)
hl.foreground("Constant", col.red:increase_red(3):darken(2))
hl.foreground("Decorator", col.yellow)
hl.foreground("Define", col.magenta)
hl.foreground("Delimeter", col.blue)
hl.foreground("Exception", col.bright_green)
hl.foreground("Float", col.magenta:increase_blue(20):desaturate(25):spin(0.1))
hl.foreground("Function", col.magenta:darken(2))
hl.foreground("Identifier", col.bright_green)
hl.foreground("Include", col.blue:darken(4):increase_blue(2))
hl.foreground("Keyword", col.blue:increase_green(5):darken(5):increase_blue(15))
hl.foreground("Label", col.red)
hl.foreground("Number", col.bright_cyan)
hl.foreground("Operator", col.cyan)
hl.foreground("PreProc", col.red:darken(3):increase_red(1))
hl.foreground("Repeat", col.bright_magenta)
hl.foreground("Special", col.bright_red)
hl.foreground("SpecialChar", col.magenta)
hl.foreground("SpecialKey", col.yellow, { deco.B })
hl.foreground("Statement", col.red)
hl.foreground("StorageClass", col.red:darken(5))
hl.foreground("String", col.green)
hl.foreground("Structure", col.bright_blue)
hl.foreground("Tag", col.blue)
hl.foreground("Todo", col.yellow)
hl.foreground("Type", col.red)
hl.foreground("Typedef", col.magenta)
hl.foreground("Macro", col.red:lighten(5))
hl.foreground("Exception", col.yellow:darken(2))
hl.foreground("NonText", col.bright_black:lighten(5))
hl.background("MatchParen", col.black:lighten(8), { deco.B })

---vim:filetype=lua
