hl.short_set("NotifyINFOBody", col.bright_black, col.blue)
hl.short_set("NotifyINFOBorder", col.bright_black, col.bright_black)
hl.short_set("NotifyINFOIcon", col.bright_black, col.bright_blue)
hl.short_set("NotifyINFOTitle", col.bright_black, col.blue)
hl.short_set("NotifyWARNBody", col.bright_black, col.yellow)
hl.short_set("NotifyWARNIcon", col.bright_black, col.bright_yellow)
hl.short_set("NotifyWARNTitle", col.bright_black, col.yellow)
hl.short_set("NotifyWARNBorder", col.bright_black, col.bright_black)
hl.short_set("NotifyDEBUGBody", col.bright_black, col.magenta)
hl.short_set("NotifyDEBUGIcon", col.bright_black, col.bright_magenta)
hl.short_set("NotifyDEBUGTitle", col.bright_black, col.magenta)
hl.short_set("NotifyDEBUGBorder", col.bright_black, col.magenta)
hl.short_set("NotifyERRORBody", col.bright_black, col.red)
hl.short_set("NotifyERRORIcon", col.bright_black, col.bright_red)
hl.short_set("NotifyERRORTitle", col.bright_black, col.red)
hl.short_set("NotifyERRORBorder", col.bright_black, col.bright_black)
hl.short_set("NotifyTRACEBody", col.bright_black, col.green)
hl.short_set("NotifyTRACEIcon", col.bright_black, col.bright_green)
hl.short_set("NotifyTRACETitle", col.bright_black, col.green)
hl.short_set("NotifyTRACEBorder", col.bright_black, col.bright_black)

---vim:filetype=lua
