hl.short_set("TelescopePreviewBorder", col.black:darken(1), col.black:darken(1))
hl.short_set("TelescopePreviewLine", col.black:darken(1), col.blue)
hl.short_set("TelescopePreviewNormal", col.black:darken(1), col.white:darken(10))
hl.short_set("TelescopePreviewTitle", col.blue, col.black)
hl.short_set("TelescopeResultsNormal", col.black:darken(2), col.white:darken(10))
hl.short_set("TelescopeResultsBorder", col.black:darken(2), col.black:darken(2))
hl.short_set("TelescopeResultsTitle", col.green, col.black)
hl.short_set("TelescopeSelection", col.black, col.bright_cyan)
hl.short_set("TelescopeSelectionCaret", col.black, col.bright_red)
hl.short_set("TelescopePromptNormal", col.bright_black:darken(1.5), col.white:darken(10))
hl.short_set("TelescopePromptBorder", col.bright_black:darken(1.5), col.bright_black:darken(1.5))
hl.short_set("TelescopePromptTitle", col.red, col.black)
hl.short_set("TelescopePromptPrefix", col.bright_black:darken(1.5), col.red)
hl.short_set("TelescopePromptCounter", col.bright_black:darken(1.5), col.magenta:spin(0.1), { deco.B })
hl.foreground("TelescopeMatching", col.magenta:increase_red(10):decrease_blue(5), { deco.B })

---vim:filetype=lua
