local Color = require("colo.color")

return {
  author = "FrenzyExists",
  name = "aquarium",
  description = "Aquarium, a simple vibrant theme.",
  source = "https://github.com/frenzyexists/aquarium-vim",
  background = "dark",
  black = Color:new({ hex = "#20202A" }),
  red = Color:new({ hex = "#EBB9B9" }),
  green = Color:new({ hex = "#BEE0A8" }),
  yellow = Color:new({ hex = "#E8CCA7" }),
  blue = Color:new({ hex = "#A7B7D6" }),
  magenta = Color:new({ hex = "#F6BBE7" }),
  cyan = Color:new({ hex = "#B8DEEB" }),
  white = Color:new({ hex = "#CED4DF" }),
  bright_black = Color:new({ hex = "#2C2E3E" }),
  bright_red = Color:new({ hex = "#EAC1C1" }),
  bright_green = Color:new({ hex = "#B1DBA4" }),
  bright_yellow = Color:new({ hex = "#E6DFB8" }),
  bright_blue = Color:new({ hex = "#C6D0E9" }),
  bright_magenta = Color:new({ hex = "#E8B6E9" }),
  bright_cyan = Color:new({ hex = "#CDDBF9" }),
  bright_white = Color:new({ hex = "#C5CBD6" }),
}
