local Color = require("colo.color")

return {
  author = "",
  name = "base16_atelier_sulphurpool",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/light/base16-atelier-sulphurpool.json",
  background = "light",
  black = Color:new({ hex = "#f5f7ff" }),
  red = Color:new({ hex = "#c94922" }),
  green = Color:new({ hex = "#ac9739" }),
  yellow = Color:new({ hex = "#c08b30" }),
  blue = Color:new({ hex = "#3d8fd1" }),
  magenta = Color:new({ hex = "#6679cc" }),
  cyan = Color:new({ hex = "#22a2c9" }),
  white = Color:new({ hex = "#5e6687" }),
  bright_black = Color:new({ hex = "#898ea4" }),
  bright_red = Color:new({ hex = "#c94922" }),
  bright_green = Color:new({ hex = "#ac9739" }),
  bright_yellow = Color:new({ hex = "#c08b30" }),
  bright_blue = Color:new({ hex = "#3d8fd1" }),
  bright_magenta = Color:new({ hex = "#6679cc" }),
  bright_cyan = Color:new({ hex = "#22a2c9" }),
  bright_white = Color:new({ hex = "#202746" }),
}