local Color = require("colo.color")

return {
  author = "",
  name = "base16_atelier_lakeside",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/light/base16-atelier-lakeside.json",
  background = "light",
  black = Color:new({ hex = "#ebf8ff" }),
  red = Color:new({ hex = "#d22d72" }),
  green = Color:new({ hex = "#568c3b" }),
  yellow = Color:new({ hex = "#8a8a0f" }),
  blue = Color:new({ hex = "#257fad" }),
  magenta = Color:new({ hex = "#6b6bb8" }),
  cyan = Color:new({ hex = "#2d8f6f" }),
  white = Color:new({ hex = "#516d7b" }),
  bright_black = Color:new({ hex = "#7195a8" }),
  bright_red = Color:new({ hex = "#d22d72" }),
  bright_green = Color:new({ hex = "#568c3b" }),
  bright_yellow = Color:new({ hex = "#8a8a0f" }),
  bright_blue = Color:new({ hex = "#257fad" }),
  bright_magenta = Color:new({ hex = "#6b6bb8" }),
  bright_cyan = Color:new({ hex = "#2d8f6f" }),
  bright_white = Color:new({ hex = "#161b1d" }),
}