local Color = require("colo.color")

return {
  author = "",
  name = "base16_apathy",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/base16-apathy.json",
  background = "dark",
  black = Color:new({ hex = "#031A16" }),
  red = Color:new({ hex = "#3E9688" }),
  green = Color:new({ hex = "#883E96" }),
  yellow = Color:new({ hex = "#3E4C96" }),
  blue = Color:new({ hex = "#96883E" }),
  magenta = Color:new({ hex = "#4C963E" }),
  cyan = Color:new({ hex = "#963E4C" }),
  white = Color:new({ hex = "#81B5AC" }),
  bright_black = Color:new({ hex = "#2B685E" }),
  bright_red = Color:new({ hex = "#3E9688" }),
  bright_green = Color:new({ hex = "#883E96" }),
  bright_yellow = Color:new({ hex = "#3E4C96" }),
  bright_blue = Color:new({ hex = "#96883E" }),
  bright_magenta = Color:new({ hex = "#4C963E" }),
  bright_cyan = Color:new({ hex = "#963E4C" }),
  bright_white = Color:new({ hex = "#D2E7E4" }),
}
