local Color = require("colo.color")

return {
  author = "",
  name = "base16_brushtrees",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/base16-brushtrees.json",
  background = "dark",
  black = Color:new({ hex = "#485867" }),
  red = Color:new({ hex = "#b38686" }),
  green = Color:new({ hex = "#87b386" }),
  yellow = Color:new({ hex = "#aab386" }),
  blue = Color:new({ hex = "#868cb3" }),
  magenta = Color:new({ hex = "#b386b2" }),
  cyan = Color:new({ hex = "#86b3b3" }),
  white = Color:new({ hex = "#B0C5C8" }),
  bright_black = Color:new({ hex = "#8299A1" }),
  bright_red = Color:new({ hex = "#b38686" }),
  bright_green = Color:new({ hex = "#87b386" }),
  bright_yellow = Color:new({ hex = "#aab386" }),
  bright_blue = Color:new({ hex = "#868cb3" }),
  bright_magenta = Color:new({ hex = "#b386b2" }),
  bright_cyan = Color:new({ hex = "#86b3b3" }),
  bright_white = Color:new({ hex = "#E3EFEF" }),
}