local Color = require("colo.color")

return {
  author = "",
  name = "base16_atelier_savanna",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/base16-atelier-savanna.json",
  background = "dark",
  black = Color:new({ hex = "#171c19" }),
  red = Color:new({ hex = "#b16139" }),
  green = Color:new({ hex = "#489963" }),
  yellow = Color:new({ hex = "#a07e3b" }),
  blue = Color:new({ hex = "#478c90" }),
  magenta = Color:new({ hex = "#55859b" }),
  cyan = Color:new({ hex = "#1c9aa0" }),
  white = Color:new({ hex = "#87928a" }),
  bright_black = Color:new({ hex = "#5f6d64" }),
  bright_red = Color:new({ hex = "#b16139" }),
  bright_green = Color:new({ hex = "#489963" }),
  bright_yellow = Color:new({ hex = "#a07e3b" }),
  bright_blue = Color:new({ hex = "#478c90" }),
  bright_magenta = Color:new({ hex = "#55859b" }),
  bright_cyan = Color:new({ hex = "#1c9aa0" }),
  bright_white = Color:new({ hex = "#ecf4ee" }),
}