local Color = require("colo.color")

return {
  author = "",
  name = "base16_atelier_plateau",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/light/base16-atelier-plateau.json",
  background = "light",
  black = Color:new({ hex = "#f4ecec" }),
  red = Color:new({ hex = "#ca4949" }),
  green = Color:new({ hex = "#4b8b8b" }),
  yellow = Color:new({ hex = "#a06e3b" }),
  blue = Color:new({ hex = "#7272ca" }),
  magenta = Color:new({ hex = "#8464c4" }),
  cyan = Color:new({ hex = "#5485b6" }),
  white = Color:new({ hex = "#585050" }),
  bright_black = Color:new({ hex = "#7e7777" }),
  bright_red = Color:new({ hex = "#ca4949" }),
  bright_green = Color:new({ hex = "#4b8b8b" }),
  bright_yellow = Color:new({ hex = "#a06e3b" }),
  bright_blue = Color:new({ hex = "#7272ca" }),
  bright_magenta = Color:new({ hex = "#8464c4" }),
  bright_cyan = Color:new({ hex = "#5485b6" }),
  bright_white = Color:new({ hex = "#1b1818" }),
}