local Color = require("colo.color")

return {
  author = "AlphaTechnolog",
  name = "decay_darkest",
  description = "Decay is a theme that uses shades of green along with a dark-toned background for better contrast!. The contrast between background and primary color helps avoiding any eye fatigue when spending a lot of time in front of the computer.",
  source = "https://github.com/AlphaTechnolog",
  background = "dark",
  black = Color:new({ hex = "#0d0f18" }),
  red = Color:new({ hex = "#dd6777" }),
  green = Color:new({ hex = "#90ceaa" }),
  yellow = Color:new({ hex = "#ecd3a0" }),
  blue = Color:new({ hex = "#86aaec" }),
  magenta = Color:new({ hex = "#c296eb" }),
  cyan = Color:new({ hex = "#93cee9" }),
  white = Color:new({ hex = "#a5b6cf" }),
  bright_black = Color:new({ hex = "#0d0f18" }),
  bright_red = Color:new({ hex = "#e26c7c" }),
  bright_green = Color:new({ hex = "#95d3af" }),
  bright_yellow = Color:new({ hex = "#f1d8a5" }),
  bright_blue = Color:new({ hex = "#8baff1" }),
  bright_magenta = Color:new({ hex = "#c79bf0" }),
  bright_cyan = Color:new({ hex = "#98d3ee" }),
  bright_white = Color:new({ hex = "#a5b6cf" }),
}