local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_prevail",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-prevail.json",
  background = "dark",
  black = Color:new({ hex = "#263139" }),
  red = Color:new({ hex = "#f36f62" }),
  green = Color:new({ hex = "#c5e19c" }),
  yellow = Color:new({ hex = "#ccb478" }),
  blue = Color:new({ hex = "#4c7e89" }),
  magenta = Color:new({ hex = "#814d61" }),
  cyan = Color:new({ hex = "#79a69d" }),
  white = Color:new({ hex = "#c4c4b5" }),
  bright_black = Color:new({ hex = "#455867" }),
  bright_red = Color:new({ hex = "#f36f62" }),
  bright_green = Color:new({ hex = "#c5e19c" }),
  bright_yellow = Color:new({ hex = "#ccb478" }),
  bright_blue = Color:new({ hex = "#4c7e89" }),
  bright_magenta = Color:new({ hex = "#814d61" }),
  bright_cyan = Color:new({ hex = "#79a69d" }),
  bright_white = Color:new({ hex = "#dbdbd1" }),
}