local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_urban",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-urban.json",
  background = "dark",
  black = Color:new({ hex = "#312e39" }),
  red = Color:new({ hex = "#87404f" }),
  green = Color:new({ hex = "#74934e" }),
  yellow = Color:new({ hex = "#ae835a" }),
  blue = Color:new({ hex = "#615772" }),
  magenta = Color:new({ hex = "#783e57" }),
  cyan = Color:new({ hex = "#554757" }),
  white = Color:new({ hex = "#c0a79a" }),
  bright_black = Color:new({ hex = "#4f4b58" }),
  bright_red = Color:new({ hex = "#87404f" }),
  bright_green = Color:new({ hex = "#74934e" }),
  bright_yellow = Color:new({ hex = "#ae835a" }),
  bright_blue = Color:new({ hex = "#615772" }),
  bright_magenta = Color:new({ hex = "#783e57" }),
  bright_cyan = Color:new({ hex = "#554757" }),
  bright_white = Color:new({ hex = "#c0a79a" }),
}