local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_scape",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-scape.json",
  background = "dark",
  black = Color:new({ hex = "#282423" }),
  red = Color:new({ hex = "#925633" }),
  green = Color:new({ hex = "#757c60" }),
  yellow = Color:new({ hex = "#987f4b" }),
  blue = Color:new({ hex = "#515962" }),
  magenta = Color:new({ hex = "#685054" }),
  cyan = Color:new({ hex = "#506168" }),
  white = Color:new({ hex = "#b7afa4" }),
  bright_black = Color:new({ hex = "#3f3d3c" }),
  bright_red = Color:new({ hex = "#925633" }),
  bright_green = Color:new({ hex = "#757c60" }),
  bright_yellow = Color:new({ hex = "#987f4b" }),
  bright_blue = Color:new({ hex = "#515962" }),
  bright_magenta = Color:new({ hex = "#685054" }),
  bright_cyan = Color:new({ hex = "#506168" }),
  bright_white = Color:new({ hex = "#b7afa4" }),
}