local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_flapr",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-flapr.json",
  background = "dark",
  black = Color:new({ hex = "#2f2832" }),
  red = Color:new({ hex = "#885d50" }),
  green = Color:new({ hex = "#747965" }),
  yellow = Color:new({ hex = "#9a8e80" }),
  blue = Color:new({ hex = "#4a4e5a" }),
  magenta = Color:new({ hex = "#76675b" }),
  cyan = Color:new({ hex = "#59555c" }),
  white = Color:new({ hex = "#bcb5b5" }),
  bright_black = Color:new({ hex = "#4a3f4e" }),
  bright_red = Color:new({ hex = "#885d50" }),
  bright_green = Color:new({ hex = "#747965" }),
  bright_yellow = Color:new({ hex = "#9a8e80" }),
  bright_blue = Color:new({ hex = "#4a4e5a" }),
  bright_magenta = Color:new({ hex = "#76675b" }),
  bright_cyan = Color:new({ hex = "#59555c" }),
  bright_white = Color:new({ hex = "#dddada" }),
}