local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_owl",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-owl.json",
  background = "dark",
  black = Color:new({ hex = "#2f2b2c" }),
  red = Color:new({ hex = "#5a5a5a" }),
  green = Color:new({ hex = "#989898" }),
  yellow = Color:new({ hex = "#cacaca" }),
  blue = Color:new({ hex = "#656565" }),
  magenta = Color:new({ hex = "#b1b1b1" }),
  cyan = Color:new({ hex = "#7f7f7f" }),
  white = Color:new({ hex = "#dedede" }),
  bright_black = Color:new({ hex = "#504c4e" }),
  bright_red = Color:new({ hex = "#5a5a5a" }),
  bright_green = Color:new({ hex = "#989898" }),
  bright_yellow = Color:new({ hex = "#cacaca" }),
  bright_blue = Color:new({ hex = "#656565" }),
  bright_magenta = Color:new({ hex = "#b1b1b1" }),
  bright_cyan = Color:new({ hex = "#7f7f7f" }),
  bright_white = Color:new({ hex = "#FFFFFF" }),
}