local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_5725",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-5725.json",
  background = "dark",
  black = Color:new({ hex = "#353234" }),
  red = Color:new({ hex = "#97544d" }),
  green = Color:new({ hex = "#97a293" }),
  yellow = Color:new({ hex = "#c29f6f" }),
  blue = Color:new({ hex = "#5e606c" }),
  magenta = Color:new({ hex = "#7a6054" }),
  cyan = Color:new({ hex = "#78746c" }),
  white = Color:new({ hex = "#c3c1b8" }),
  bright_black = Color:new({ hex = "#5c575b" }),
  bright_red = Color:new({ hex = "#97544d" }),
  bright_green = Color:new({ hex = "#97a293" }),
  bright_yellow = Color:new({ hex = "#c29f6f" }),
  bright_blue = Color:new({ hex = "#5e606c" }),
  bright_magenta = Color:new({ hex = "#7a6054" }),
  bright_cyan = Color:new({ hex = "#78746c" }),
  bright_white = Color:new({ hex = "#c3c1b8" }),
}