local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_blok",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-blok.json",
  background = "dark",
  black = Color:new({ hex = "#2c2a2b" }),
  red = Color:new({ hex = "#a67979" }),
  green = Color:new({ hex = "#809f7b" }),
  yellow = Color:new({ hex = "#baad8a" }),
  blue = Color:new({ hex = "#6d7575" }),
  magenta = Color:new({ hex = "#7d6969" }),
  cyan = Color:new({ hex = "#7b9899" }),
  white = Color:new({ hex = "#bab9ba" }),
  bright_black = Color:new({ hex = "#545253" }),
  bright_red = Color:new({ hex = "#a67979" }),
  bright_green = Color:new({ hex = "#809f7b" }),
  bright_yellow = Color:new({ hex = "#baad8a" }),
  bright_blue = Color:new({ hex = "#6d7575" }),
  bright_magenta = Color:new({ hex = "#7d6969" }),
  bright_cyan = Color:new({ hex = "#7b9899" }),
  bright_white = Color:new({ hex = "#bab9ba" }),
}