local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_book",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-book.json",
  background = "dark",
  black = Color:new({ hex = "#2b2b28" }),
  red = Color:new({ hex = "#993f3c" }),
  green = Color:new({ hex = "#78855e" }),
  yellow = Color:new({ hex = "#937b5a" }),
  blue = Color:new({ hex = "#415265" }),
  magenta = Color:new({ hex = "#885458" }),
  cyan = Color:new({ hex = "#646666" }),
  white = Color:new({ hex = "#c4c3c0" }),
  bright_black = Color:new({ hex = "#c4c3c0" }),
  bright_red = Color:new({ hex = "#993f3c" }),
  bright_green = Color:new({ hex = "#78855e" }),
  bright_yellow = Color:new({ hex = "#937b5a" }),
  bright_blue = Color:new({ hex = "#415265" }),
  bright_magenta = Color:new({ hex = "#885458" }),
  bright_cyan = Color:new({ hex = "#646666" }),
  bright_white = Color:new({ hex = "#c4c3c0" }),
}