local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_kit",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-kit.json",
  background = "dark",
  black = Color:new({ hex = "#272733" }),
  red = Color:new({ hex = "#d65f2f" }),
  green = Color:new({ hex = "#aabf7f" }),
  yellow = Color:new({ hex = "#dabe72" }),
  blue = Color:new({ hex = "#5e7e9b" }),
  magenta = Color:new({ hex = "#bf6c68" }),
  cyan = Color:new({ hex = "#5a7273" }),
  white = Color:new({ hex = "#cac5b7" }),
  bright_black = Color:new({ hex = "#48485e" }),
  bright_red = Color:new({ hex = "#d65f2f" }),
  bright_green = Color:new({ hex = "#aabf7f" }),
  bright_yellow = Color:new({ hex = "#dabe72" }),
  bright_blue = Color:new({ hex = "#5e7e9b" }),
  bright_magenta = Color:new({ hex = "#bf6c68" }),
  bright_cyan = Color:new({ hex = "#5a7273" }),
  bright_white = Color:new({ hex = "#d5d1c6" }),
}