local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_pastely",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-pastely.json",
  background = "dark",
  black = Color:new({ hex = "#2c2c2e" }),
  red = Color:new({ hex = "#645446" }),
  green = Color:new({ hex = "#59674f" }),
  yellow = Color:new({ hex = "#87835d" }),
  blue = Color:new({ hex = "#4d554f" }),
  magenta = Color:new({ hex = "#70614f" }),
  cyan = Color:new({ hex = "#666755" }),
  white = Color:new({ hex = "#aba786" }),
  bright_black = Color:new({ hex = "#aba786" }),
  bright_red = Color:new({ hex = "#645446" }),
  bright_green = Color:new({ hex = "#59674f" }),
  bright_yellow = Color:new({ hex = "#87835d" }),
  bright_blue = Color:new({ hex = "#4d554f" }),
  bright_magenta = Color:new({ hex = "#70614f" }),
  bright_cyan = Color:new({ hex = "#666755" }),
  bright_white = Color:new({ hex = "#c4c1aa" }),
}