local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_blend",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-blend.json",
  background = "dark",
  black = Color:new({ hex = "#272725" }),
  red = Color:new({ hex = "#7d5151" }),
  green = Color:new({ hex = "#959c4f" }),
  yellow = Color:new({ hex = "#a78749" }),
  blue = Color:new({ hex = "#455563" }),
  magenta = Color:new({ hex = "#9f908d" }),
  cyan = Color:new({ hex = "#4a5e5b" }),
  white = Color:new({ hex = "#f2f2f2" }),
  bright_black = Color:new({ hex = "#4f4f4b" }),
  bright_red = Color:new({ hex = "#7d5151" }),
  bright_green = Color:new({ hex = "#959c4f" }),
  bright_yellow = Color:new({ hex = "#a78749" }),
  bright_blue = Color:new({ hex = "#455563" }),
  bright_magenta = Color:new({ hex = "#9f908d" }),
  bright_cyan = Color:new({ hex = "#4a5e5b" }),
  bright_white = Color:new({ hex = "#ffffff" }),
}