local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_sprout",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-sprout.json",
  background = "dark",
  black = Color:new({ hex = "#2d3144" }),
  red = Color:new({ hex = "#8d6d5c" }),
  green = Color:new({ hex = "#6d806d" }),
  yellow = Color:new({ hex = "#96915d" }),
  blue = Color:new({ hex = "#68758d" }),
  magenta = Color:new({ hex = "#8a747b" }),
  cyan = Color:new({ hex = "#8d97a8" }),
  white = Color:new({ hex = "#cfccbe" }),
  bright_black = Color:new({ hex = "#525a69" }),
  bright_red = Color:new({ hex = "#8d6d5c" }),
  bright_green = Color:new({ hex = "#6d806d" }),
  bright_yellow = Color:new({ hex = "#96915d" }),
  bright_blue = Color:new({ hex = "#68758d" }),
  bright_magenta = Color:new({ hex = "#8a747b" }),
  bright_cyan = Color:new({ hex = "#8d97a8" }),
  bright_white = Color:new({ hex = "#f0efeb" }),
}