local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_branch",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-branch.json",
  background = "dark",
  black = Color:new({ hex = "#32221a" }),
  red = Color:new({ hex = "#c2562d" }),
  green = Color:new({ hex = "#96a65e" }),
  yellow = Color:new({ hex = "#d29b5a" }),
  blue = Color:new({ hex = "#3b8e8c" }),
  magenta = Color:new({ hex = "#c47e5b" }),
  cyan = Color:new({ hex = "#639a90" }),
  white = Color:new({ hex = "#cfc1a9" }),
  bright_black = Color:new({ hex = "#564a45" }),
  bright_red = Color:new({ hex = "#c2562d" }),
  bright_green = Color:new({ hex = "#96a65e" }),
  bright_yellow = Color:new({ hex = "#d29b5a" }),
  bright_blue = Color:new({ hex = "#3b8e8c" }),
  bright_magenta = Color:new({ hex = "#c47e5b" }),
  bright_cyan = Color:new({ hex = "#639a90" }),
  bright_white = Color:new({ hex = "#cfc1a9" }),
}