local Color = require("colo.color")

return {
  author = "",
  name = "dkeg_forst",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/dkeg-forst.json",
  background = "dark",
  black = Color:new({ hex = "#161f14" }),
  red = Color:new({ hex = "#744425" }),
  green = Color:new({ hex = "#50703f" }),
  yellow = Color:new({ hex = "#806420" }),
  blue = Color:new({ hex = "#56535d" }),
  magenta = Color:new({ hex = "#71532f" }),
  cyan = Color:new({ hex = "#45605d" }),
  white = Color:new({ hex = "#aca173" }),
  bright_black = Color:new({ hex = "#2d352b" }),
  bright_red = Color:new({ hex = "#744425" }),
  bright_green = Color:new({ hex = "#50703f" }),
  bright_yellow = Color:new({ hex = "#806420" }),
  bright_blue = Color:new({ hex = "#56535d" }),
  bright_magenta = Color:new({ hex = "#71532f" }),
  bright_cyan = Color:new({ hex = "#45605d" }),
  bright_white = Color:new({ hex = "#aca173" }),
}