local Color = require("colo.color")

return {
  author = "TorchedSammy",
  name = "macos",
  description = "",
  source = "https://github.com/TorchedSammy/dotfiles/blob/master/.config/awesome/themes/colors/macos.lua",
  background = "dark",
  black = Color:new({ hex = "#0e1112" }),
  red = Color:new({ hex = "#ed5f5c" }),
  green = Color:new({ hex = "#5ee26b" }),
  yellow = Color:new({ hex = "#f3b94c" }),
  blue = Color:new({ hex = "#307cf5" }),
  magenta = Color:new({ hex = "#e25f9b" }),
  cyan = Color:new({ hex = "#6ef0e3" }),
  white = Color:new({ hex = "#dfdfdf" }),
  bright_black = Color:new({ hex = "#0e1112" }),
  bright_red = Color:new({ hex = "#ed5f5c" }),
  bright_green = Color:new({ hex = "#5ee26b" }),
  bright_yellow = Color:new({ hex = "#f3b94c" }),
  bright_blue = Color:new({ hex = "#307cf5" }),
  bright_magenta = Color:new({ hex = "#e25f9b" }),
  bright_cyan = Color:new({ hex = "#6ef0e3" }),
  bright_white = Color:new({ hex = "#dfdfdf" }),
}