local Color = require("colo.color")

return {
  author = "Manas",
  name = "paradise",
  description = "The Paradise Theme.",
  source = "https://github.com/paradise-theme/paradise",
  background = "dark",
  black = Color:new({ hex = "#151515" }),
  red = Color:new({ hex = "#B66467" }),
  green = Color:new({ hex = "#8C977D" }),
  yellow = Color:new({ hex = "#D9BC8C" }),
  blue = Color:new({ hex = "#8DA3B9" }),
  magenta = Color:new({ hex = "#A988B0" }),
  cyan = Color:new({ hex = "#8AA6A2" }),
  white = Color:new({ hex = "#E8E3E3" }),
  bright_black = Color:new({ hex = "#2E2E2E" }),
  bright_red = Color:new({ hex = "#B66467" }),
  bright_green = Color:new({ hex = "#8C977D" }),
  bright_yellow = Color:new({ hex = "#D9BC8C" }),
  bright_blue = Color:new({ hex = "#8DA3B9" }),
  bright_magenta = Color:new({ hex = "#A988B0" }),
  bright_cyan = Color:new({ hex = "#8AA6A2" }),
  bright_white = Color:new({ hex = "#BBB6B6" }),
}