local Color = require("colo.color")

return {
  author = "",
  name = "sexy_splurge",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-splurge.json",
  background = "dark",
  black = Color:new({ hex = "#4a4b4a" }),
  red = Color:new({ hex = "#d7699a" }),
  green = Color:new({ hex = "#80d468" }),
  yellow = Color:new({ hex = "#d7a169" }),
  blue = Color:new({ hex = "#6985d7" }),
  magenta = Color:new({ hex = "#c86ad4" }),
  cyan = Color:new({ hex = "#6fccd1" }),
  white = Color:new({ hex = "#dbdcdc" }),
  bright_black = Color:new({ hex = "#696969" }),
  bright_red = Color:new({ hex = "#d7699a" }),
  bright_green = Color:new({ hex = "#80d468" }),
  bright_yellow = Color:new({ hex = "#d7a169" }),
  bright_blue = Color:new({ hex = "#6985d7" }),
  bright_magenta = Color:new({ hex = "#c86ad4" }),
  bright_cyan = Color:new({ hex = "#6fccd1" }),
  bright_white = Color:new({ hex = "#dbdcdc" }),
}