local Color = require("colo.color")

return {
  author = "",
  name = "sexy_rasi",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-rasi.json",
  background = "dark",
  black = Color:new({ hex = "#1b1d1e" }),
  red = Color:new({ hex = "#f92672" }),
  green = Color:new({ hex = "#82b414" }),
  yellow = Color:new({ hex = "#fd971f" }),
  blue = Color:new({ hex = "#4e82aa" }),
  magenta = Color:new({ hex = "#8c54fe" }),
  cyan = Color:new({ hex = "#465457" }),
  white = Color:new({ hex = "#ccccc6" }),
  bright_black = Color:new({ hex = "#505354" }),
  bright_red = Color:new({ hex = "#f92672" }),
  bright_green = Color:new({ hex = "#82b414" }),
  bright_yellow = Color:new({ hex = "#fd971f" }),
  bright_blue = Color:new({ hex = "#4e82aa" }),
  bright_magenta = Color:new({ hex = "#8c54fe" }),
  bright_cyan = Color:new({ hex = "#465457" }),
  bright_white = Color:new({ hex = "#ccccc6" }),
}