local Color = require("colo.color")

return {
  author = "",
  name = "sexy_monokai",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-monokai.json",
  background = "dark",
  black = Color:new({ hex = "#48483e" }),
  red = Color:new({ hex = "#dc2566" }),
  green = Color:new({ hex = "#8fc029" }),
  yellow = Color:new({ hex = "#d4c96e" }),
  blue = Color:new({ hex = "#55bcce" }),
  magenta = Color:new({ hex = "#9358fe" }),
  cyan = Color:new({ hex = "#56b7a5" }),
  white = Color:new({ hex = "#acada1" }),
  bright_black = Color:new({ hex = "#76715e" }),
  bright_red = Color:new({ hex = "#dc2566" }),
  bright_green = Color:new({ hex = "#8fc029" }),
  bright_yellow = Color:new({ hex = "#d4c96e" }),
  bright_blue = Color:new({ hex = "#55bcce" }),
  bright_magenta = Color:new({ hex = "#9358fe" }),
  bright_cyan = Color:new({ hex = "#56b7a5" }),
  bright_white = Color:new({ hex = "#acada1" }),
}