local Color = require("colo.color")

return {
  author = "",
  name = "sexy_neon",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-neon.json",
  background = "dark",
  black = Color:new({ hex = "#171717" }),
  red = Color:new({ hex = "#d81765" }),
  green = Color:new({ hex = "#97d01a" }),
  yellow = Color:new({ hex = "#ffa800" }),
  blue = Color:new({ hex = "#16b1fb" }),
  magenta = Color:new({ hex = "#ff2491" }),
  cyan = Color:new({ hex = "#0fdcb6" }),
  white = Color:new({ hex = "#ebebeb" }),
  bright_black = Color:new({ hex = "#38252c" }),
  bright_red = Color:new({ hex = "#d81765" }),
  bright_green = Color:new({ hex = "#97d01a" }),
  bright_yellow = Color:new({ hex = "#ffa800" }),
  bright_blue = Color:new({ hex = "#16b1fb" }),
  bright_magenta = Color:new({ hex = "#ff2491" }),
  bright_cyan = Color:new({ hex = "#0fdcb6" }),
  bright_white = Color:new({ hex = "#ebebeb" }),
}