local Color = require("colo.color")

return {
  author = "",
  name = "sexy_derp",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-derp.json",
  background = "dark",
  black = Color:new({ hex = "#111111" }),
  red = Color:new({ hex = "#d36265" }),
  green = Color:new({ hex = "#aece91" }),
  yellow = Color:new({ hex = "#e7e18c" }),
  blue = Color:new({ hex = "#5297cf" }),
  magenta = Color:new({ hex = "#963c59" }),
  cyan = Color:new({ hex = "#5e7175" }),
  white = Color:new({ hex = "#bebebe" }),
  bright_black = Color:new({ hex = "#666666" }),
  bright_red = Color:new({ hex = "#d36265" }),
  bright_green = Color:new({ hex = "#aece91" }),
  bright_yellow = Color:new({ hex = "#e7e18c" }),
  bright_blue = Color:new({ hex = "#5297cf" }),
  bright_magenta = Color:new({ hex = "#963c59" }),
  bright_cyan = Color:new({ hex = "#5e7175" }),
  bright_white = Color:new({ hex = "#bebebe" }),
}