local Color = require("colo.color")

return {
  author = "",
  name = "sexy_navy_and_ivory",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-navy-and-ivory.json",
  background = "dark",
  black = Color:new({ hex = "#032c36" }),
  red = Color:new({ hex = "#c2454e" }),
  green = Color:new({ hex = "#7cbf9e" }),
  yellow = Color:new({ hex = "#8a7a63" }),
  blue = Color:new({ hex = "#2e3340" }),
  magenta = Color:new({ hex = "#ff5879" }),
  cyan = Color:new({ hex = "#44b5b1" }),
  white = Color:new({ hex = "#f2f1b9" }),
  bright_black = Color:new({ hex = "#065f73" }),
  bright_red = Color:new({ hex = "#c2454e" }),
  bright_green = Color:new({ hex = "#7cbf9e" }),
  bright_yellow = Color:new({ hex = "#8a7a63" }),
  bright_blue = Color:new({ hex = "#2e3340" }),
  bright_magenta = Color:new({ hex = "#ff5879" }),
  bright_cyan = Color:new({ hex = "#44b5b1" }),
  bright_white = Color:new({ hex = "#f2f1b9" }),
}