local Color = require("colo.color")

return {
  author = "",
  name = "sexy_belge",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-belge.json",
  background = "dark",
  black = Color:new({ hex = "#252525" }),
  red = Color:new({ hex = "#ef6769" }),
  green = Color:new({ hex = "#a6e22e" }),
  yellow = Color:new({ hex = "#fd971f" }),
  blue = Color:new({ hex = "#6495ed" }),
  magenta = Color:new({ hex = "#deb887" }),
  cyan = Color:new({ hex = "#b0c4de" }),
  white = Color:new({ hex = "#dbdcdc" }),
  bright_black = Color:new({ hex = "#454545" }),
  bright_red = Color:new({ hex = "#ef6769" }),
  bright_green = Color:new({ hex = "#a6e22e" }),
  bright_yellow = Color:new({ hex = "#fd971f" }),
  bright_blue = Color:new({ hex = "#6495ed" }),
  bright_magenta = Color:new({ hex = "#deb887" }),
  bright_cyan = Color:new({ hex = "#b0c4de" }),
  bright_white = Color:new({ hex = "#dbdcdc" }),
}