local Color = require("colo.color")

return {
  author = "",
  name = "sexy_mikado",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-mikado.json",
  background = "dark",
  black = Color:new({ hex = "#322a2c" }),
  red = Color:new({ hex = "#a04363" }),
  green = Color:new({ hex = "#9b9329" }),
  yellow = Color:new({ hex = "#bf7a29" }),
  blue = Color:new({ hex = "#6a8c8c" }),
  magenta = Color:new({ hex = "#856774" }),
  cyan = Color:new({ hex = "#757978" }),
  white = Color:new({ hex = "#bcbcaf" }),
  bright_black = Color:new({ hex = "#46423b" }),
  bright_red = Color:new({ hex = "#a04363" }),
  bright_green = Color:new({ hex = "#9b9329" }),
  bright_yellow = Color:new({ hex = "#bf7a29" }),
  bright_blue = Color:new({ hex = "#6a8c8c" }),
  bright_magenta = Color:new({ hex = "#856774" }),
  bright_cyan = Color:new({ hex = "#757978" }),
  bright_white = Color:new({ hex = "#bcbcaf" }),
}