local Color = require("colo.color")

return {
  author = "",
  name = "sexy_hybrid",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-hybrid.json",
  background = "dark",
  black = Color:new({ hex = "#393939" }),
  red = Color:new({ hex = "#da4939" }),
  green = Color:new({ hex = "#9acc79" }),
  yellow = Color:new({ hex = "#d0d26b" }),
  blue = Color:new({ hex = "#6d9cbe" }),
  magenta = Color:new({ hex = "#9f5079" }),
  cyan = Color:new({ hex = "#435d75" }),
  white = Color:new({ hex = "#c2c2c2" }),
  bright_black = Color:new({ hex = "#474747" }),
  bright_red = Color:new({ hex = "#da4939" }),
  bright_green = Color:new({ hex = "#9acc79" }),
  bright_yellow = Color:new({ hex = "#d0d26b" }),
  bright_blue = Color:new({ hex = "#6d9cbe" }),
  bright_magenta = Color:new({ hex = "#9f5079" }),
  bright_cyan = Color:new({ hex = "#435d75" }),
  bright_white = Color:new({ hex = "#c2c2c2" }),
}