local Color = require("colo.color")

return {
  author = "",
  name = "sexy_hund",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-hund.json",
  background = "dark",
  black = Color:new({ hex = "#222222" }),
  red = Color:new({ hex = "#E84F4F" }),
  green = Color:new({ hex = "#B7CE42" }),
  yellow = Color:new({ hex = "#FEA63C" }),
  blue = Color:new({ hex = "#66AABB" }),
  magenta = Color:new({ hex = "#B7416E" }),
  cyan = Color:new({ hex = "#6D878D" }),
  white = Color:new({ hex = "#DDDDDD" }),
  bright_black = Color:new({ hex = "#666666" }),
  bright_red = Color:new({ hex = "#E84F4F" }),
  bright_green = Color:new({ hex = "#B7CE42" }),
  bright_yellow = Color:new({ hex = "#FEA63C" }),
  bright_blue = Color:new({ hex = "#66AABB" }),
  bright_magenta = Color:new({ hex = "#B7416E" }),
  bright_cyan = Color:new({ hex = "#6D878D" }),
  bright_white = Color:new({ hex = "#DDDDDD" }),
}