local Color = require("colo.color")

return {
  author = "",
  name = "sexy_phrak1",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-phrak1.json",
  background = "dark",
  black = Color:new({ hex = "#000000" }),
  red = Color:new({ hex = "#a80000" }),
  green = Color:new({ hex = "#00a800" }),
  yellow = Color:new({ hex = "#a85400" }),
  blue = Color:new({ hex = "#0000a8" }),
  magenta = Color:new({ hex = "#a800a8" }),
  cyan = Color:new({ hex = "#00a8a8" }),
  white = Color:new({ hex = "#a8a8a8" }),
  bright_black = Color:new({ hex = "#545054" }),
  bright_red = Color:new({ hex = "#a80000" }),
  bright_green = Color:new({ hex = "#00a800" }),
  bright_yellow = Color:new({ hex = "#a85400" }),
  bright_blue = Color:new({ hex = "#0000a8" }),
  bright_magenta = Color:new({ hex = "#a800a8" }),
  bright_cyan = Color:new({ hex = "#00a8a8" }),
  bright_white = Color:new({ hex = "#a8a8a8" }),
}