local Color = require("colo.color")

return {
  author = "",
  name = "sexy_doomicideocean",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-doomicideocean.json",
  background = "dark",
  black = Color:new({ hex = "#000000" }),
  red = Color:new({ hex = "#571dc2" }),
  green = Color:new({ hex = "#14db49" }),
  yellow = Color:new({ hex = "#403d70" }),
  blue = Color:new({ hex = "#385a70" }),
  magenta = Color:new({ hex = "#384894" }),
  cyan = Color:new({ hex = "#4f3a5e" }),
  white = Color:new({ hex = "#999999" }),
  bright_black = Color:new({ hex = "#38372c" }),
  bright_red = Color:new({ hex = "#571dc2" }),
  bright_green = Color:new({ hex = "#14db49" }),
  bright_yellow = Color:new({ hex = "#403d70" }),
  bright_blue = Color:new({ hex = "#385a70" }),
  bright_magenta = Color:new({ hex = "#384894" }),
  bright_cyan = Color:new({ hex = "#4f3a5e" }),
  bright_white = Color:new({ hex = "#999999" }),
}