local Color = require("colo.color")

return {
  author = "",
  name = "sexy_pretty_and_pastel",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-pretty-and-pastel.json",
  background = "dark",
  black = Color:new({ hex = "#292929" }),
  red = Color:new({ hex = "#CF6A4C" }),
  green = Color:new({ hex = "#19CB00" }),
  yellow = Color:new({ hex = "#FAD07A" }),
  blue = Color:new({ hex = "#8197BF" }),
  magenta = Color:new({ hex = "#8787AF" }),
  cyan = Color:new({ hex = "#668799" }),
  white = Color:new({ hex = "#888888" }),
  bright_black = Color:new({ hex = "#525252" }),
  bright_red = Color:new({ hex = "#CF6A4C" }),
  bright_green = Color:new({ hex = "#19CB00" }),
  bright_yellow = Color:new({ hex = "#FAD07A" }),
  bright_blue = Color:new({ hex = "#8197BF" }),
  bright_magenta = Color:new({ hex = "#8787AF" }),
  bright_cyan = Color:new({ hex = "#668799" }),
  bright_white = Color:new({ hex = "#888888" }),
}