local Color = require("colo.color")

return {
  author = "",
  name = "sexy_astromouse",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-astromouse.json",
  background = "dark",
  black = Color:new({ hex = "#1c1c1c" }),
  red = Color:new({ hex = "#d770af" }),
  green = Color:new({ hex = "#9acc79" }),
  yellow = Color:new({ hex = "#d0d26b" }),
  blue = Color:new({ hex = "#77b6c5" }),
  magenta = Color:new({ hex = "#a488d9" }),
  cyan = Color:new({ hex = "#7fcab3" }),
  white = Color:new({ hex = "#8d8d8d" }),
  bright_black = Color:new({ hex = "#3d3a3a" }),
  bright_red = Color:new({ hex = "#d770af" }),
  bright_green = Color:new({ hex = "#9acc79" }),
  bright_yellow = Color:new({ hex = "#d0d26b" }),
  bright_blue = Color:new({ hex = "#77b6c5" }),
  bright_magenta = Color:new({ hex = "#a488d9" }),
  bright_cyan = Color:new({ hex = "#7fcab3" }),
  bright_white = Color:new({ hex = "#8d8d8d" }),
}