local Color = require("colo.color")

return {
  author = "",
  name = "sexy_sexcolors",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-sexcolors.json",
  background = "dark",
  black = Color:new({ hex = "#252525" }),
  red = Color:new({ hex = "#ff9f95" }),
  green = Color:new({ hex = "#a6e22e" }),
  yellow = Color:new({ hex = "#fd971f" }),
  blue = Color:new({ hex = "#435e87" }),
  magenta = Color:new({ hex = "#789ec6" }),
  cyan = Color:new({ hex = "#5e7175" }),
  white = Color:new({ hex = "#dbdcdc" }),
  bright_black = Color:new({ hex = "#454545" }),
  bright_red = Color:new({ hex = "#ff9f95" }),
  bright_green = Color:new({ hex = "#a6e22e" }),
  bright_yellow = Color:new({ hex = "#fd971f" }),
  bright_blue = Color:new({ hex = "#435e87" }),
  bright_magenta = Color:new({ hex = "#789ec6" }),
  bright_cyan = Color:new({ hex = "#5e7175" }),
  bright_white = Color:new({ hex = "#dbdcdc" }),
}