local Color = require("colo.color")

return {
  author = "",
  name = "sexy_mostly_bright",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/light/sexy-mostly-bright.json",
  background = "light",
  black = Color:new({ hex = "#D3D3D3" }),
  red = Color:new({ hex = "#EF6B7B" }),
  green = Color:new({ hex = "#A1D569" }),
  yellow = Color:new({ hex = "#F59335" }),
  blue = Color:new({ hex = "#4EC2E8" }),
  magenta = Color:new({ hex = "#FEC7CD" }),
  cyan = Color:new({ hex = "#95C1C0" }),
  white = Color:new({ hex = "#707070" }),
  bright_black = Color:new({ hex = "#B3B3B3" }),
  bright_red = Color:new({ hex = "#EF6B7B" }),
  bright_green = Color:new({ hex = "#A1D569" }),
  bright_yellow = Color:new({ hex = "#F59335" }),
  bright_blue = Color:new({ hex = "#4EC2E8" }),
  bright_magenta = Color:new({ hex = "#FEC7CD" }),
  bright_cyan = Color:new({ hex = "#95C1C0" }),
  bright_white = Color:new({ hex = "#707070" }),
}