local Color = require("colo.color")

return {
  author = "",
  name = "sexy_trim_yer_beard",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-trim-yer-beard.json",
  background = "dark",
  black = Color:new({ hex = "#0F0E0D" }),
  red = Color:new({ hex = "#845336" }),
  green = Color:new({ hex = "#57553C" }),
  yellow = Color:new({ hex = "#A17E3E" }),
  blue = Color:new({ hex = "#43454F" }),
  magenta = Color:new({ hex = "#604848" }),
  cyan = Color:new({ hex = "#5C6652" }),
  white = Color:new({ hex = "#A18B62" }),
  bright_black = Color:new({ hex = "#383332" }),
  bright_red = Color:new({ hex = "#845336" }),
  bright_green = Color:new({ hex = "#57553C" }),
  bright_yellow = Color:new({ hex = "#A17E3E" }),
  bright_blue = Color:new({ hex = "#43454F" }),
  bright_magenta = Color:new({ hex = "#604848" }),
  bright_cyan = Color:new({ hex = "#5C6652" }),
  bright_white = Color:new({ hex = "#A18B62" }),
}