local Color = require("colo.color")

return {
  author = "",
  name = "sexy_thwump",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-thwump.json",
  background = "dark",
  black = Color:new({ hex = "#202020" }),
  red = Color:new({ hex = "#a07070" }),
  green = Color:new({ hex = "#70a070" }),
  yellow = Color:new({ hex = "#a0a070" }),
  blue = Color:new({ hex = "#7070a0" }),
  magenta = Color:new({ hex = "#a070a0" }),
  cyan = Color:new({ hex = "#70a0a0" }),
  white = Color:new({ hex = "#a0a0a0" }),
  bright_black = Color:new({ hex = "#505050" }),
  bright_red = Color:new({ hex = "#a07070" }),
  bright_green = Color:new({ hex = "#70a070" }),
  bright_yellow = Color:new({ hex = "#a0a070" }),
  bright_blue = Color:new({ hex = "#7070a0" }),
  bright_magenta = Color:new({ hex = "#a070a0" }),
  bright_cyan = Color:new({ hex = "#70a0a0" }),
  bright_white = Color:new({ hex = "#a0a0a0" }),
}