local Color = require("colo.color")

return {
  author = "",
  name = "sexy_gnometerm",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-gnometerm.json",
  background = "dark",
  black = Color:new({ hex = "#000000" }),
  red = Color:new({ hex = "#cc0000" }),
  green = Color:new({ hex = "#4e9a06" }),
  yellow = Color:new({ hex = "#c4a000" }),
  blue = Color:new({ hex = "#3465a4" }),
  magenta = Color:new({ hex = "#75507b" }),
  cyan = Color:new({ hex = "#06989a" }),
  white = Color:new({ hex = "#d3d7cf" }),
  bright_black = Color:new({ hex = "#555753" }),
  bright_red = Color:new({ hex = "#cc0000" }),
  bright_green = Color:new({ hex = "#4e9a06" }),
  bright_yellow = Color:new({ hex = "#c4a000" }),
  bright_blue = Color:new({ hex = "#3465a4" }),
  bright_magenta = Color:new({ hex = "#75507b" }),
  bright_cyan = Color:new({ hex = "#06989a" }),
  bright_white = Color:new({ hex = "#d3d7cf" }),
}