local Color = require("colo.color")

return {
  author = "",
  name = "sexy_s3r0_modified",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-s3r0-modified.json",
  background = "dark",
  black = Color:new({ hex = "#4A3637" }),
  red = Color:new({ hex = "#D17B49" }),
  green = Color:new({ hex = "#7B8748" }),
  yellow = Color:new({ hex = "#AF865A" }),
  blue = Color:new({ hex = "#535C5C" }),
  magenta = Color:new({ hex = "#775759" }),
  cyan = Color:new({ hex = "#6D715E" }),
  white = Color:new({ hex = "#C0B18B" }),
  bright_black = Color:new({ hex = "#785f60" }),
  bright_red = Color:new({ hex = "#D17B49" }),
  bright_green = Color:new({ hex = "#7B8748" }),
  bright_yellow = Color:new({ hex = "#AF865A" }),
  bright_blue = Color:new({ hex = "#535C5C" }),
  bright_magenta = Color:new({ hex = "#775759" }),
  bright_cyan = Color:new({ hex = "#6D715E" }),
  bright_white = Color:new({ hex = "#C0B18B" }),
}