local Color = require("colo.color")

return {
  author = "",
  name = "sexy_gjm",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-gjm.json",
  background = "dark",
  black = Color:new({ hex = "#1c1c1c" }),
  red = Color:new({ hex = "#ff005b" }),
  green = Color:new({ hex = "#cee318" }),
  yellow = Color:new({ hex = "#ffe755" }),
  blue = Color:new({ hex = "#048ac7" }),
  magenta = Color:new({ hex = "#833c9f" }),
  cyan = Color:new({ hex = "#0ac1cd" }),
  white = Color:new({ hex = "#e5e5e5" }),
  bright_black = Color:new({ hex = "#666666" }),
  bright_red = Color:new({ hex = "#ff005b" }),
  bright_green = Color:new({ hex = "#cee318" }),
  bright_yellow = Color:new({ hex = "#ffe755" }),
  bright_blue = Color:new({ hex = "#048ac7" }),
  bright_magenta = Color:new({ hex = "#833c9f" }),
  bright_cyan = Color:new({ hex = "#0ac1cd" }),
  bright_white = Color:new({ hex = "#e5e5e5" }),
}