local Color = require("colo.color")

return {
  author = "",
  name = "sexy_dawn",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-dawn.json",
  background = "dark",
  black = Color:new({ hex = "#353535" }),
  red = Color:new({ hex = "#744B40" }),
  green = Color:new({ hex = "#6D6137" }),
  yellow = Color:new({ hex = "#765636" }),
  blue = Color:new({ hex = "#61564B" }),
  magenta = Color:new({ hex = "#6B4A49" }),
  cyan = Color:new({ hex = "#435861" }),
  white = Color:new({ hex = "#B3B3B3" }),
  bright_black = Color:new({ hex = "#5F5F5F" }),
  bright_red = Color:new({ hex = "#744B40" }),
  bright_green = Color:new({ hex = "#6D6137" }),
  bright_yellow = Color:new({ hex = "#765636" }),
  bright_blue = Color:new({ hex = "#61564B" }),
  bright_magenta = Color:new({ hex = "#6B4A49" }),
  bright_cyan = Color:new({ hex = "#435861" }),
  bright_white = Color:new({ hex = "#B3B3B3" }),
}