local Color = require("colo.color")

return {
  author = "",
  name = "sexy_gotham",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-gotham.json",
  background = "dark",
  black = Color:new({ hex = "#0a0f14" }),
  red = Color:new({ hex = "#c33027" }),
  green = Color:new({ hex = "#26a98b" }),
  yellow = Color:new({ hex = "#edb54b" }),
  blue = Color:new({ hex = "#195465" }),
  magenta = Color:new({ hex = "#4e5165" }),
  cyan = Color:new({ hex = "#33859d" }),
  white = Color:new({ hex = "#98d1ce" }),
  bright_black = Color:new({ hex = "#364b61" }),
  bright_red = Color:new({ hex = "#c33027" }),
  bright_green = Color:new({ hex = "#26a98b" }),
  bright_yellow = Color:new({ hex = "#edb54b" }),
  bright_blue = Color:new({ hex = "#195465" }),
  bright_magenta = Color:new({ hex = "#4e5165" }),
  bright_cyan = Color:new({ hex = "#33859d" }),
  bright_white = Color:new({ hex = "#98d1ce" }),
}