local Color = require("colo.color")

return {
  author = "",
  name = "sexy_insignificato",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/sexy-insignificato.json",
  background = "dark",
  black = Color:new({ hex = "#3d3e3d" }),
  red = Color:new({ hex = "#755a5b" }),
  green = Color:new({ hex = "#68755a" }),
  yellow = Color:new({ hex = "#756e5a" }),
  blue = Color:new({ hex = "#5b6976" }),
  magenta = Color:new({ hex = "#755b76" }),
  cyan = Color:new({ hex = "#5b7674" }),
  white = Color:new({ hex = "#808080" }),
  bright_black = Color:new({ hex = "#5a5b5c" }),
  bright_red = Color:new({ hex = "#755a5b" }),
  bright_green = Color:new({ hex = "#68755a" }),
  bright_yellow = Color:new({ hex = "#756e5a" }),
  bright_blue = Color:new({ hex = "#5b6976" }),
  bright_magenta = Color:new({ hex = "#755b76" }),
  bright_cyan = Color:new({ hex = "#5b7674" }),
  bright_white = Color:new({ hex = "#808080" }),
}