local Color = require("colo.color")

return {
  author = "TorchedSammy",
  name = "stardew_default",
  description = "",
  source = "https://github.com/TorchedSammy/dotfiles/blob/master/.config/awesome/themes/colors/stardew.lua",
  background = "light",
  black = Color:new({ hex = "#ffffff" }),
  red = Color:new({ hex = "#e34f4f" }),
  green = Color:new({ hex = "#20C073" }),
  yellow = Color:new({ hex = "#e3974f" }),
  blue = Color:new({ hex = "#4fa0e3" }),
  magenta = Color:new({ hex = "#884fe3" }),
  cyan = Color:new({ hex = "#4fe3cf" }),
  white = Color:new({ hex = "#403e3e" }),
  bright_black = Color:new({ hex = "#ffffff" }),
  bright_red = Color:new({ hex = "#e34f4f" }),
  bright_green = Color:new({ hex = "#20C073" }),
  bright_yellow = Color:new({ hex = "#e3974f" }),
  bright_blue = Color:new({ hex = "#4fa0e3" }),
  bright_magenta = Color:new({ hex = "#884fe3" }),
  bright_cyan = Color:new({ hex = "#4fe3cf" }),
  bright_white = Color:new({ hex = "#403e3e" }),
}