local Color = require("colo.color")

return {
  author = "",
  name = "tempus_spring",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/tempus_spring.json",
  background = "dark",
  black = Color:new({ hex = "#34403c" }),
  red = Color:new({ hex = "#ff855a" }),
  green = Color:new({ hex = "#6ab78a" }),
  yellow = Color:new({ hex = "#b6aa1a" }),
  blue = Color:new({ hex = "#5daeee" }),
  magenta = Color:new({ hex = "#d495b4" }),
  cyan = Color:new({ hex = "#6eb2bc" }),
  white = Color:new({ hex = "#a5a8a7" }),
  bright_black = Color:new({ hex = "#96aca7" }),
  bright_red = Color:new({ hex = "#df993a" }),
  bright_green = Color:new({ hex = "#4abb88" }),
  bright_yellow = Color:new({ hex = "#99b22a" }),
  bright_blue = Color:new({ hex = "#3caffe" }),
  bright_magenta = Color:new({ hex = "#d091db" }),
  bright_cyan = Color:new({ hex = "#4ab4d3" }),
  bright_white = Color:new({ hex = "#a5a8a7" }),
}