local Color = require("colo.color")

return {
  author = "",
  name = "tempus_summer",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/dark/tempus_summer.json",
  background = "dark",
  black = Color:new({ hex = "#293345" }),
  red = Color:new({ hex = "#fe6d32" }),
  green = Color:new({ hex = "#6ba86d" }),
  yellow = Color:new({ hex = "#af9a0a" }),
  blue = Color:new({ hex = "#679ed7" }),
  magenta = Color:new({ hex = "#bc8ab6" }),
  cyan = Color:new({ hex = "#6ea590" }),
  white = Color:new({ hex = "#9b999e" }),
  bright_black = Color:new({ hex = "#a39799" }),
  bright_red = Color:new({ hex = "#df8251" }),
  bright_green = Color:new({ hex = "#7aa747" }),
  bright_yellow = Color:new({ hex = "#ba953a" }),
  bright_blue = Color:new({ hex = "#3ba1e8" }),
  bright_magenta = Color:new({ hex = "#c97ed7" }),
  bright_cyan = Color:new({ hex = "#52a6b1" }),
  bright_white = Color:new({ hex = "#9b999e" }),
}