local Color = require("colo.color")

return {
  author = "",
  name = "tempus_past",
  description = "",
  source = "https://github.com/dylanaraps/pywal/tree/master/pywal/colorschemes/light/tempus_past.json",
  background = "light",
  black = Color:new({ hex = "#dadce8" }),
  red = Color:new({ hex = "#c01c10" }),
  green = Color:new({ hex = "#2a7000" }),
  yellow = Color:new({ hex = "#825a0a" }),
  blue = Color:new({ hex = "#025ccd" }),
  magenta = Color:new({ hex = "#a43878" }),
  cyan = Color:new({ hex = "#49628d" }),
  white = Color:new({ hex = "#63606b" }),
  bright_black = Color:new({ hex = "#80565d" }),
  bright_red = Color:new({ hex = "#b43036" }),
  bright_green = Color:new({ hex = "#007214" }),
  bright_yellow = Color:new({ hex = "#91520a" }),
  bright_blue = Color:new({ hex = "#5046eb" }),
  bright_magenta = Color:new({ hex = "#ba166b" }),
  bright_cyan = Color:new({ hex = "#076c76" }),
  bright_white = Color:new({ hex = "#63606b" }),
}